version: '3.8'

services:
  # Service Base de données
  mongodb:
    image: mongo:latest
    container_name: adonis_mongo
    restart: always
    ports:
      - '27017:27017' # Port standard Mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db # Persistance des données

  # Service Interface Graphique (Optionnel mais recommandé)
  mongo-express:
    image: mongo-express
    container_name: adonis_mongo_ui
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: false # Désactive le login pour l'interface web (en dev local)

volumes:
  mongo_data:
